// automatically generated by build.xml for new releases
      
/////////////////////////////////////////////////////////////////////////////
//
// Project   ProjectForge
//
// Copyright 2001-2011, Kai Reinhard
//           Dual-licensed.
//
/////////////////////////////////////////////////////////////////////////////

package org.projectforge;

public class AppVersion
{
  public static final String APP_ID = "ProjectForge";

  public static final String APP_TITLE = "ProjectForge 2011";

  public static final Version VERSION = new Version("3.6.0");

  public static final String NUMBER = VERSION.toString();

  public static final String RELEASE_DATE = "2011-03-18";

  public static final String RELEASE_TIMESTAMP = "2011-03-18 07:54";
}

			