// automatically generated by build.xml for new releases
      
/////////////////////////////////////////////////////////////////////////////
//
// Project   ProjectForge
//
// Copyright 2001-2012, Kai Reinhard
//           Dual-licensed.
//
/////////////////////////////////////////////////////////////////////////////

package org.projectforge;

public class AppVersion
{
  public static final String APP_ID = "ProjectForge";

  public static final String APP_TITLE = "ProjectForge 2012";

  public static final Version VERSION = new Version("4.1.4.9");

  public static final String NUMBER = VERSION.toString();

  public static final String RELEASE_DATE = "2012-10-17";

  public static final String RELEASE_TIMESTAMP = "2012-10-17 23:58";
}

			