// automatically generated by build.xml for new releases
      
/////////////////////////////////////////////////////////////////////////////
//
// Project   ProjectForge
//
// Copyright 2001-2011, Kai Reinhard
//           Dual-licensed.
//
/////////////////////////////////////////////////////////////////////////////

package org.projectforge;

public class Version
{
  public static final String APP_ID = "ProjectForge";

  public static final String APP_TITLE = "ProjectForge 2011";

  public static final String NUMBER = "3.5.3";

  public static final String RELEASE_DATE = "2011-02-14";

  public static final String RELEASE_TIMESTAMP = "2011-02-14 10:00";
}

		