// automatically generated by build.xml for new releases
      
/////////////////////////////////////////////////////////////////////////////
//
// Project   ProjectForge
//
// Copyright 2001-2010, Kai Reinhard
//           Dual-licensed.
//
/////////////////////////////////////////////////////////////////////////////

package org.projectforge;

public class Version
{
  public static final String APP_ID = "ProjectForge";

  public static final String APP_TITLE = "ProjectForge 2010";

  public static final String NUMBER = "3.4.2";

  public static final String RELEASE_DATE = "2010-11-08";

  public static final String RELEASE_TIMESTAMP = "2010-11-08 00:36";
}

		